on:
  schedule:
    # Update on every 00:00 GMT+7 which means 17:00 UTC
    # TODO: ideally GMT+9 people get this first
    - cron: "0 17 * * *"

jobs:
  update_katla:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"
      - name: install deps
        run: npm ci
      - name: update new word
        run: npm run update
        env:
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
